//
// Created by Lukasz Fabia on 02/11/2023.
//

#ifndef EFFECTIVE_PROGRAMMING_TECHNIQUES_CFIXEXPRESSION_H
#define EFFECTIVE_PROGRAMMING_TECHNIQUES_CFIXEXPRESSION_H


class CFixExpression {

};


#endif //EFFECTIVE_PROGRAMMING_TECHNIQUES_CFIXEXPRESSION_H
