//
// Created by ufabi on 18.11.2023.
//

#ifndef EFFECTIVE_PROGRAMMING_TECHNIQUES_INTERFACE_H
#define EFFECTIVE_PROGRAMMING_TECHNIQUES_INTERFACE_H


class Interface {

};


#endif //EFFECTIVE_PROGRAMMING_TECHNIQUES_INTERFACE_H
