//
// Created by ufabi on 20.10.2023.
//

#ifndef EFFECTIVE_PROGRAMMING_TECHNIQUES_CINTERFACE_H
#define EFFECTIVE_PROGRAMMING_TECHNIQUES_CINTERFACE_H


class CInterface {

};


#endif //EFFECTIVE_PROGRAMMING_TECHNIQUES_CINTERFACE_H
